### ISSUE TITLE
Does Referral Source work on Joomla

### ISSUE THREAD

**Issue by nybc-se** [twomice/com.joineryhq.referralsource#5]
I don't see this extension in my extension list.  I'm on Civi 5.74.4, so I don't think it's a Civi version issue, so wondering if it's because I'm on Joomla or if it is something else.  Any guidance appreciated.

**Comment by twomice** [comment]
That's just because this extension is not marked with the "Reviewed Extension" status; if it were, you'd find it in CiviCRM's in-app extensions management page. 

But because it's not, the only way to install is by one of the methods mentioned in the docs at [System Administrator Guide > Extensions > How to install an extension](https://docs.civicrm.org/sysadmin/en/latest/customize/extensions/#how-to-install-an-extension), specifically in one of these sections on that page:
- Installing from the command line
- Installing from a .zip file
- Installing from a code repository (GitLab, CodeBerg, GitHub, ...)

I hope this helps!
